version: "3.9"
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: elastic
    environment: 
      - discovery.type=single-node
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - ./stack/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports: 
      - 9200:9200
      - 9300:9300 
    networks: 
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.1
    container_name: logstash
    depends_on: 
      - elasticsearch
    volumes:
      - ./stack/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./stack/logstash-pipeline.conf:/usr/share/logstash/pipeline/logstash.conf
    ports: 
      - 9001:9001
    networks: 
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: kibana
    environment: 
      - ELASTICSEARCH_HOSTS=http://elastic:9200
      - SERVER_HOST=0.0.0.0
    depends_on: 
      - elasticsearch
    volumes:
      - ./stack/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports: 
      - 5601:5601
    networks: 
      - elastic
      
networks: 
  elastic:
